version: "3.9"
services:
  rest_api_springboot:
    build: .
    container_name: Api_Rest_Contenedor
    ports:
      - "8080:8080"
    depends_on:
      - mysql_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/apirest_docker
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234567
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.cj.jdbc.Driver

  mysql_db:
    image: mysql:8.0
    container_name: MySQL_Contenedor
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234567
      - MYSQL_DATABASE=apirest_docker
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
