server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: create
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/apirest_docker?useSSL=false
    username: root
    password: 1234567
    driver-class-name: com.mysql.cj.jdbc.Driver